HW29 is done
Milka44/AQA-playwright pull request #11
Opened 2024-08-22 08:23 UTC by Milka44

2024-08-22 12:05 UTC, sttaran requested changes

2024-08-22 12:05 UTC, sttaran commented on src/pageObjects/controllers/UserController.js
> +    return this._request.post(this.#LOGIN_USER_PATH, {data:requestBody})}
where requestBody comes from?

2024-08-22 12:05 UTC, sttaran commented on src/pageObjects/controllers/UserController.js
> +    return this._request.post(this.#LOGIN_USER_PATH, {data:requestBody})}
why loginNewUser? 

I would consider renaming this method

2024-08-22 12:05 UTC, sttaran commented on src/pageObjects/fixtures/userGaragePageFixture.js
> +    }, { auto: true }],
you don't use this new user

2024-08-22 12:05 UTC, sttaran commented on src/pageObjects/fixtures/userGaragePageFixture.js
> +        const response = await carsController.createCar(requestBody);
carsController uses context from the first user

2024-08-22 12:05 UTC, sttaran commented on tests/api/garage/createCarWithController.spec.js
> +    });
do not use newCar fixture for this test

2024-08-22 12:05 UTC, sttaran commented on tests/api/garage/createCarWithController.spec.js
> +    });
create a car right in the test

2024-08-22 12:05 UTC, sttaran commented on tests/api/garage/getAllCarBrandsWithController.spec.js
> +        expect(fetchedBrandsData).toMatchObject(CARBRANDS);
use toEqual

2024-08-22 12:05 UTC, sttaran commented on tests/api/garage/getAllCarmodels.spec.js
> +        expect(fetchedModelsData).toEqual(CARMODELS);
I would suggest to compare CARMODELS to comparable format

2024-08-22 12:05 UTC, sttaran commented on tests/api/garage/getCarBrandById.spec.js
> +        expect(fetchedBrandData).toMatchObject({
first argument should be actual data

2024-08-22 12:05 UTC, sttaran commented on tests/api/garage/getUserCarByIDController.spec.js
> +
compare whole response body

2024-08-22 12:05 UTC, sttaran commented on tests/api/garage/getUsersCarsWithController.spec.js
> +        }));
use one toEqual instead

compare whole response body

2024-08-22 12:05 UTC, sttaran commented on tests/api/garage/modifyCarWithController.spec.js
> +        expect(response.data.mileage).toBeGreaterThanOrEqual(newCar.mileage);
toBe modifiedCar.mileage

2024-08-22 12:05 UTC, sttaran commented on tests/api/garage/modifyCarWithController.spec.js
> +        expect(moment(response.data.carCreatedAt).isValid(), "Date should be valid").toBeTruthy();
this value should not be changed

check it

2024-08-23 12:57 UTC, Milka44 commented on src/pageObjects/fixtures/userGaragePageFixture.js
> +    }, { auto: true }],
ні, як раз юзаю через { auto: true }- у всіх тестах створюється новий юзер. Тк. не змогла розділити використання реквесту з storageState: USER1_STORAGE_STATE_PATH та newUser ( все ламається ...)

2024-08-23 14:07 UTC, Milka44 commented on tests/api/garage/modifyCarWithController.spec.js
> +        expect(moment(response.data.carCreatedAt).isValid(), "Date should be valid").toBeTruthy();
Я пробувала - можна змінити і модель и бренд наряду з витратами, тому так і зробила сценарій але тест переписала і доповнила. Додам в новому PR

2024-08-23 14:08 UTC, Milka44 commented on tests/api/garage/modifyCarWithController.spec.js
> +        expect(response.data.mileage).toBeGreaterThanOrEqual(newCar.mileage);
виправлю в новому PR

2024-08-23 14:08 UTC, Milka44 commented on tests/api/garage/getUserCarByIDController.spec.js
> +
виправлю в новому PR

2024-08-23 14:08 UTC, Milka44 commented on tests/api/garage/getUsersCarsWithController.spec.js
> +        }));
виправлю в новому PR

2024-08-23 14:08 UTC, Milka44 commented on tests/api/garage/getCarBrandById.spec.js
> +        expect(fetchedBrandData).toMatchObject({
виправлю в новому PR

2024-08-23 14:08 UTC, Milka44 commented on tests/api/garage/getAllCarBrandsWithController.spec.js
> +        expect(fetchedBrandsData).toMatchObject(CARBRANDS);
виправлю в новому PR

2024-08-23 14:08 UTC, Milka44 commented on tests/api/garage/createCarWithController.spec.js
> +    });
виправлю в новому PR

2024-08-23 14:09 UTC, Milka44 commented on src/pageObjects/controllers/UserController.js
> +    return this._request.post(this.#LOGIN_USER_PATH, {data:requestBody})}
виправлю в новому PR

2024-08-23 14:17 UTC, closed without merging